name: CI

on: [push, pull_request]

jobs:

  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2

    - name: Set environment variables
      id: vars
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=sha_long::$(git rev-parse HEAD)"

    - name: Dependency packages (apt)
      run: |
        sudo apt update
        sudo apt -y install git python3-pip zip

    - name: Dependency packages (pip)
      run: python3 -m pip install --user bitarray crcmod pyserial requests

    - name: Build dist
      run: |
        P=greaseweazle-tools
        V=${{ steps.vars.outputs.sha_short }}
        VL=${{ steps.vars.outputs.sha_long }}
        make dist VER=$V
        rm $P-$V.zip
        rm $P-$V/RELEASE_NOTES
        echo "$VL" >$P-$V/COMMIT
        echo "commit = '$VL'" >>$P-$V/scripts/greaseweazle/version.py 
        zip -r $P-$V.zip $P-$V

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: greaseweazle-tools.ci.${{ steps.vars.outputs.sha_short }}
        path: greaseweazle-tools-${{ steps.vars.outputs.sha_short }}.zip

  build-windows:
    runs-on: windows-2019
    steps:

    - uses: actions/checkout@v2

    - name: Set environment variables
      id: vars
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=sha_long::$(git rev-parse HEAD)"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x86

    - name: Dependency packages (pip)
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --user bitarray crcmod pyserial requests cx_Freeze

    - name: Build dist
      run: |
        $P="greaseweazle-tools"
        $V="${{ steps.vars.outputs.sha_short }}"
        $VL="${{ steps.vars.outputs.sha_long }}"
        make dist VER=$V
        rm $P-$V.zip
        rm $P-$V/RELEASE_NOTES
        echo "$VL" >$P-$V/COMMIT
        echo "commit = '$VL'" >>$P-$V/scripts/greaseweazle/version.py 
        make _windist VER=$V

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: greaseweazle-tools.ci.${{ steps.vars.outputs.sha_short }}
        path: greaseweazle-tools-${{ steps.vars.outputs.sha_short }}-win.zip

  finalise:
    needs: [build-ubuntu, build-windows]
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2

    - name: Set environment variables
      id: vars
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: greaseweazle-tools.ci.${{ steps.vars.outputs.sha_short }}

    - name: Fix up Windows distribution
      run: |
        P=greaseweazle-tools
        V=${{ steps.vars.outputs.sha_short }}
        unzip $P-$V-win.zip
        find $P-$V -name 'api-ms-*' | xargs rm -f
        find $P-$V/lib -name 'python*.dll' | xargs rm -f
        find $P-$V/lib -name 'vcruntime140.dll' | xargs rm -f
        rm $P-$V-win.zip
        zip -r $P-$V-win.zip $P-$V

    - name: Upload finalised artifacts
      uses: actions/upload-artifact@v2
      with:
        name: greaseweazle-tools.ci.${{ steps.vars.outputs.sha_short }}
        path: greaseweazle-tools-${{ steps.vars.outputs.sha_short }}-win.zip
